#!/usr/bin/bash
## Programa para que la vaca hacker diga algo
##  Requiere:
##    - xcowsay
##    - cowsay
##    - Estatuto del Hacker: https://github.com/ubuntuperonista/Estatuto-del-Hacker


### Ajustar las Variables:
COOKIE="fortune doctrina"
FUENTE="mono 22"
### Indica la imagen del personaje que quieres usar:
IMAGEN="/usr/share/xcowsay/vaca.png"

${COOKIE} | xcowsay --image=${IMAGEN} --font="${FUENTE}" --cow-size=large
